# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/walde/Documents/Unreal Projects/MyProject3/MyProject3.uproject

TARGETS = \
	MyProject3-Linux-DebugGame  \
	MyProject3-Linux-Shipping  \
	MyProject3 \
	MyProject3Editor-Linux-DebugGame  \
	MyProject3Editor-Linux-Shipping  \
	MyProject3Editor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MyProject3Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MyProject3Editor-Linux-Debug


MyProject3-Linux-DebugGame:
	 $(PROJECTBUILD) MyProject3 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MyProject3-Linux-Shipping:
	 $(PROJECTBUILD) MyProject3 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MyProject3:
	 $(PROJECTBUILD) MyProject3 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MyProject3Editor-Linux-DebugGame:
	 $(PROJECTBUILD) MyProject3Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MyProject3Editor-Linux-Shipping:
	 $(PROJECTBUILD) MyProject3Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MyProject3Editor:
	 $(PROJECTBUILD) MyProject3Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
